### ISSUE TITLE
lower end of version range should not be included in output

### ISSUE THREAD

**Issue by stopfstedt** [jrjohnson/generate-github-release-notes#3] opened 2019-01-22 17:28 UTC
case in point:

```
*   8b66100 - (HEAD -> master, tag: v1.3.1, upstream/master) Merge pull request #266 from stopfstedt/fix_rl_indicators (10 hours ago) <Stefan Topfstedt>
|\  
| * b98b41c - (origin/fix_rl_indicators, fix_rl_indicators) fixed switcheroo. (10 hours ago) <Stefan Topfstedt>
|/  
*   87ff923 - (tag: v1.3.0, origin/master, origin/HEAD) Merge pull request #264 from stopfstedt/restricted_lists (20 hours ago) <Stefan Topfstedt>
```

running ` generate-github-release-notes thronesdb thronesdb v1.3.0 v1.3.1` yields:

```
# v1.3.1

## [v1.3.1](https://github.com/thronesdb/thronesdb/tree/v1.3.1)

[Full Changelog](https://github.com/thronesdb/thronesdb/compare/v1.3.0...v1.3.1)


**Fixed Bugs:**

- restricted list indicators in &quot;my decks&quot; are reversed [\#265](https://github.com/ThronesDB/thronesdb/issues/265)


**Closed issues:**

- Restricted Lists validation and indicators [\#247](https://github.com/ThronesDB/thronesdb/issues/247)

**Merged pull requests:**

- fixed switcheroo. [\#266](https://github.com/ThronesDB/thronesdb/pull/266) [@stopfstedt](https://github.com/stopfstedt)
- Restricted list indicators [\#264](https://github.com/ThronesDB/thronesdb/pull/264) [@stopfstedt](https://github.com/stopfstedt)


\* *These notes were automatically created by [generate-github-release-notes](https://github.com/jrjohnson/generate-github-release-notes)*

```

the line items pertaining to issues 247 and 264 should not be part of the output.

**Comment by jrjohnson** [comment] 2019-02-07 04:11
This seems to be a weakness in the github API. I think these show up because we can only find things merged since a date https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-when-an-issue-or-pull-request-was-closed but the parameter is only granular to the day and these two tags are on the same day.

**Comment by jrjohnson** [comment] 2019-02-09 23:04
I made a change in #12, but it doesn't seem to help. Unless I'm reading this wrong though your tag happened *before* the problem issues were merged. Since github issues aren't tied to a commit I can't just use the commit history, I have to go back and look at the date.

Closed on:
<img width="549" alt="closed on" src="https://user-images.githubusercontent.com/349624/52527337-f8e70500-2c7b-11e9-9cf5-b13862941c98.png">

tagged at:
<img width="469" alt="tagged at" src="https://user-images.githubusercontent.com/349624/52527339-fb495f00-2c7b-11e9-9cfe-9484bca06aa6.png">

**Closed** 2020-04-05 23:38 UTC
